name: release

on:
  workflow_dispatch:
  create:
    tags:
      - '*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: 'Set up JDK'
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: 'Prepare git'
        run: git config --global core.autocrlf false

      - name: 'Prepare branch name'
        if: (github.event_name == 'create' && github.event.ref_type == 'tag')
        run: >
          echo "refName=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: 'Checkout relevant branch'
        uses: actions/checkout@v3
        with:
          ref: ${{ env.refName }}

      - name: 'Set up Graal'
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Compile'
        run: mvn --no-transfer-progress clean package

      - name: 'Run'
        run: ./target/app.exe

      - name: 'Upload'
        uses: actions/upload-artifact@v3
        with:
          name: the-app
          path: ./target/app.exe
